language: r
cache:
- packages
os: linux
dist: "xenial"
warnings_are_errors: false

r_packages:
  - covr
  - remotes

addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
    update: true

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=3
  - source activate test-environment
  - conda install git pip
  - pip install git+git://github.com/weecology/retriever@master
  # - conda install -c conda-forge retriever
  - retriever
  - python -c 'import retriever;retriever.check_for_updates()'
  - R -e 'remotes::install_github("ropensci/rdataretriever")'

jobs:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
    - rm README.Rmd
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::codecov()'
    - bash deploy_compendium.sh
    deploy:
      strategy: git
      provider: pages
      token: $GITHUB_PAT
      keep_history: true
      local_dir: docs
      skip_cleanup: true
      on:
        branch: master
  