language: r
cache:
- packages
- pip
sudo: required
dist: "trusty"
warnings_are_errors: false

r_packages:
  - covr
  - callr

addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
      - libgsl0ldbl
    update: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libudunits2-dev
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade git+https://git@github.com/weecology/retriever.git

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master
